python-interpreter-path = "E:/mugil/a3  express cargo/backend/.venv/Scripts/python.exe"
search-path = [
    "E:/mugil/a3  express cargo/backend",
    "."
]

[errors]
missing-import = "ignore"
missing-attribute = "ignore"
reportAttributeAccessIssue = "ignore"
